"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[in](text)\
$directory\
$git_branch\
$git_status\
[at](text)\
$time
$character
"""

palette = "main"

[palettes.main]
pink = '#f5c2e7'
red = '#f38ba8'
teal = '#94e2d5'
sky = '#89dceb'
mauve = '#cba6f7'
green = '#a6e3a1'
peach = '#fab387'
base = '#1e1e2e'
text = '#cdd6f4'
subtext = '#bac2de'

[character]
disabled = false
success_symbol = '[λ](bold fg:green)'
error_symbol = '[λ](bold fg:red)'
vimcmd_symbol = '[λ](bold fg:creen)'
vimcmd_replace_one_symbol = '[<](bold fg:mauve)'
vimcmd_replace_symbol = '[<](bold fg:mauve)'
vimcmd_visual_symbol = '[<](bold fg:lavender)'


[username]
show_always = true
style_user = "fg:pink"
style_root = "fg:pink"
format = '[$user ]($style)'

[line_break]
disabled = false

[directory]
disabled = false
style = "mauve"
format = "[ $path ]($style)"

[os]
disabled = false
style = "pink"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[git_branch]
disabled = false
style = "mauve"
symbol = " "
format = "[on ](text)[$symbol$branch(:remote_branch)]($style) "

[git_status]
style = "mauve"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "pink"
format = '[ $time]($style)'
