"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](blue)\
$os\
$username\
[](bg:lavender fg:blue)\
$directory\
[](fg:lavender bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:peach)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:peach bg:yellow)\
$docker_context\
[](fg:yellow bg:pink)\
$time\
[ ](fg:pink)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:blue fg:crust"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

#[username]
#show_always = true
#style_user = "bg:blue fg:crust"
#style_root = "bg:blue fg:crust"
#format = '[ $user ]($style)'

[directory]
style = "fg:crust bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:crust bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:crust bg:teal)]($style)'

[nodejs]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[c]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[rust]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[golang]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[php]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[java]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[kotlin]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[haskell]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[python]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:crust bg:peach)]($style)'

[docker_context]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $context) ](fg:crust bg:yellow)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:pink"
format = '[[ $time ](fg:crust bg:pink)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[λ](bold fg:green)'
error_symbol = '[λ](bold fg:red)'
vimcmd_symbol = '[λ](bold fg:creen)'
vimcmd_replace_one_symbol = '[<](bold fg:purple)'
vimcmd_replace_symbol = '[<](bold fg:purple)'
vimcmd_visual_symbol = '[<](bold fg:lavender)'
